# App Info
ios_app_id                                : 1445977851                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Stay up to date with everything Fortnite. Daily Llama is an unofficial Fortnite companion app that includes daily news articles, item shop, stats, location wheel and more! 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Chris Houston                                
your_link                                 : https://chris-houston.github.io/                     
your_city                                 :                                 
email_address                             : dev.chrishouston@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Daily Fortnite News
    description                           : Stay up to date with the new season of Fortnite with daily news articles!
    fontawesome_icon_name                 : newspaper
    
  - title                                 : Item Shop
    description                           : View the live item shop and never miss an item!
    fontawesome_icon_name                 : shopping-cart

  - title                                 : Stats
    description                           : Search any player to see in depth stats!
    fontawesome_icon_name                 : chart-bar

  - title                                 : Location Wheel
    description                           : Where we landing? Spin the wheel to decide where to land!
    fontawesome_icon_name                 : map

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.05
topbar_title_color                        : "#000000"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#eeeeee"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#15B8F1"

app_title_color                           : "#000000"
app_price_color                           : "#333333"
app_description_color                     : "#333333"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#15B8F1"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
